version: '3'

services:
  nodeapp:
    build:
      context: .
    container_name: banking-system
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres
    container_name: postgres-bank
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - './data:/var/lib/postgresql/data'
      - './dumps:/dumps'
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis-bank
    ports:
      - '6379:6379'


volumes:
  data:
    driver: local